<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
      <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\StockPilot.Application\StockPilot.Application.csproj" />
      <ProjectReference Include="..\..\Infrastructure\StockPilot.Persistence\StockPilot.Persistence.csproj" />
    </ItemGroup>

</Project>
