<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\..\Core\StockPilot.Application\StockPilot.Application.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.79" />
      <PackageReference Include="Dapper.SqlBuilder" Version="2.1.66" />
      <PackageReference Include="dbup-postgresql" Version="7.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
      <PackageReference Include="Npgsql" Version="10.0.3" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="Migrations\Scripts\*.sql" />
    </ItemGroup>
</Project>
